import PorductInterface from "@/interfaces/product";

/* export const productsUtils: PorductInterface[] = [
    {
        Descripcion: 'Camiseta Nike',
        Id_Familia: 1,
        CodigoProducto: 'P001',
        Familia: 'Ropa',
        CodigoPrecio: 'CP001',
        Precio: 29.99,
        CodigoExsitencia: 'CE001',
        Existencia: 50,
    },
    {
        Descripcion: 'Zapatos Adidas',
        Id_Familia: 2,
        CodigoProducto: 'P002',
        Familia: 'Calzado',
        CodigoPrecio: 'CP002',
        Precio: 79.99,
        CodigoExsitencia: 'CE002',
        Existencia: 20,
    },
    {
        Descripcion: 'Pantalones Levi\'s',
        Id_Familia: 3,
        CodigoProducto: 'P003',
        Familia: 'Ropa',
        CodigoPrecio: 'CP003',
        Precio: 49.99,
        CodigoExsitencia: 'CE003',
        Existencia: 30,
    },
    {
        Descripcion: 'Reloj Casio',
        Id_Familia: 4,
        CodigoProducto: 'P004',
        Familia: 'Accesorios',
        CodigoPrecio: 'CP004',
        Precio: 39.99,
        CodigoExsitencia: 'CE004',
        Existencia: 15,
    },
    {
        Descripcion: 'Televisor Samsung',
        Id_Familia: 5,
        CodigoProducto: 'P005',
        Familia: 'Electrónica',
        CodigoPrecio: 'CP005',
        Precio: 399.99,
        CodigoExsitencia: 'CE005',
        Existencia: 5,
    },
    {
        Descripcion: 'Cámara Canon',
        Id_Familia: 6,
        CodigoProducto: 'P006',
        Familia: 'Electrónica',
        CodigoPrecio: 'CP006',
        Precio: 299.99,
        CodigoExsitencia: 'CE006',
        Existencia: 8,
    },
    {
        Descripcion: 'Guitarra Fender',
        Id_Familia: 7,
        CodigoProducto: 'P007',
        Familia: 'Instrumentos',
        CodigoPrecio: 'CP007',
        Precio: 199.99,
        CodigoExsitencia: 'CE007',
        Existencia: 12,
    },
    {
        Descripcion: 'Bolso Louis Vuitton',
        Id_Familia: 8,
        CodigoProducto: 'P008',
        Familia: 'Accesorios',
        CodigoPrecio: 'CP008',
        Precio: 899.99,
        CodigoExsitencia: 'CE008',
        Existencia: 2,
    },
]; */
