import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { api } from '@/api/api'
import { GetServerSideProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ products } : any) {

  console.log({products})
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <h1 style={{ marginBottom : "50px"}}>OleiWeb</h1>

        {
          products.map( (product : any) => (
            <>
            <div className="business">
              <h3>Empresa : {product.Nombre}</h3>
              <p>Colonia : {product.Colonia}</p>
            </div>
            </>
          ))
        }

      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const response = await api.get('/api/product');
    const products = await response.data;

    console.log({ products })
    return {
      props: {
        products
      }
    };
  } catch (error) {
    console.error(error);

    return {
      props: {
        products: []
      }
    };
  }
}