import React, { ReactNode, useState } from 'react';
import { useSpring, animated } from 'react-spring';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { Toaster } from 'react-hot-toast';
import ModalCart from '../Modals/ModalCart';
import Footer from '../Navigation/Footer';
import Header from '../Navigation/Header';
import ModalMenu from '../Modals/ModalMenu';

interface Props {
    children: ReactNode
}

export const LayoutOnboarding = ({ children }: Props) => {

    const [openModalCart, setOpenModalCart] = useState(false)
    const [openModalMenu, setOpenModalMenu] = useState(false)
    const { pathname } = useRouter()
    const gradientProps = useSpring({
        from: {
            background:
                'linear-gradient(0deg, rgba(255, 255, 255, 1) 0%, rgba(237, 237, 237, 1) 47%, rgba(237, 237, 237, 1) 59%, rgba(245, 147, 212, 0.05) 86%, rgba(9, 118, 223, 0.05) 98%)',
        },
        to: async (next) => {
            while (1) {
                await next({
                    background:
                        'linear-gradient(0deg, rgba(245, 147, 212, 0.1) 0%, rgba(245, 147, 212, 0.2) 30%, rgba(245, 147, 212, 0.3) 40%, rgba(245, 147, 212, 0.4) 70%, rgba(245, 147, 212, 0.45) 100%)',
                });
                await next({
                    background:
                        'linear-gradient(0deg, rgba(255, 255, 255, 1) 0%, rgba(237, 237, 237, 1) 47%, rgba(237, 237, 237, 1) 59%, rgba(245, 147, 212, 0.05) 86%, rgba(9, 118, 223, 0.05) 100%)',
                });
            }
        },
        config: {
            duration: 6000,
        },
    });

    return (
        <>
            <animated.div
                className="gradient-background"
                style={{
                    position: 'fixed',
                    top: 0,
                    left: 0,
                    width: '100%',
                    height: '100%',
                    zIndex: -1,
                    ...gradientProps,
                }}
            />

            <Head>
                <title>Olei web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/circle-solid.svg" />
            </Head>

            <Header setOpenModalCart={setOpenModalCart} setOpenModalMenu={setOpenModalMenu}/>

            <div>
                {children}
            </div>

            <Footer />

            <ModalMenu
                visible={openModalMenu}
                onClose={() => setOpenModalMenu(false)}
            />

            <ModalCart
                visible={openModalCart}
                onClose={() => setOpenModalCart(false)}
            />

            <Toaster />
        </>
    )
}
