import FiltersInterface from '@/interfaces/filters'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { Dispatch, ReactNode, SetStateAction, useState } from 'react'
import { Toaster } from 'react-hot-toast'
import ModalCart from '../Modals/ModalCart'
import Footer from '../Navigation/Footer'
import Header from '../Navigation/Header'

interface Props {
    children: ReactNode,
    filtersActive?: FiltersInterface,
    setFiltersActive?: Dispatch<SetStateAction<FiltersInterface>>
}

export const Layout = ({ children, filtersActive, setFiltersActive }: Props) => {

    const [openModalCart, setOpenModalCart] = useState(false)
    const { pathname } = useRouter()

    return (
        <>
            <Head>
                <title>Olei web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/circle-solid.svg" />
            </Head>

            <Header
                setOpenModalCart={setOpenModalCart}
                filtersActive={filtersActive}
                setFiltersActive={setFiltersActive}
            />

            <div>
                {children}
            </div>

            {
                pathname !== "/cart" &&
                <Footer />
            }


            <ModalCart
                visible={openModalCart}
                onClose={() => setOpenModalCart(false)}
            />

            <Toaster />
        </>
    )
}
