import Head from 'next/head'
import React from 'react'
import Header from '../Navigation/Header'

interface Props {
    children : any
}

export const Layout = ({children} : Props) => {
    return (
        <>
            <Head>
                <title>Olei web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <div>
                {children}
            </div>
        </>
    )
}
