import React, { ReactNode, useContext, useState } from 'react';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { Toaster } from 'react-hot-toast';
import ModalCart from '../Modals/ModalCart';
import Footer from '../Navigation/Footer';
import Header from '../Navigation/Header/Header';
import ModalMenu from '../Modals/ModalMenu';
import Image from 'next/image';
import { AuthContext } from '@/context';

interface Props {
    children: ReactNode
}

export const Layout = ({ children }: Props) => {

    const [openModalCart, setOpenModalCart] = useState(false)
    const [openModalMenu, setOpenModalMenu] = useState(false)
    const { pathname } = useRouter()
    const { user } = useContext(AuthContext);


    const getBanner = () => {
        const database = user?.BaseSQL
        const databaseSplit = database?.split('_')
        const newPath = databaseSplit?.[1]?.toLowerCase().trim();
        const banner = newPath ? `https://oleistorage.blob.core.windows.net/${newPath}/BANNER.png` : '/bannerOlei2.png'
        return banner;
    }

    return (
        <>
            <Head>
                <title>Olei web</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/circle-solid.svg" />
            </Head>

            <Header setOpenModalCart={setOpenModalCart} setOpenModalMenu={setOpenModalMenu} />

            {
                pathname === '/products' &&
                <div className='banner'>
                    <Image
                        fill
                        alt="banner"
                        src={getBanner()}
                    />
                </div>
            }

            <div>
                {children}
            </div>

            {
                pathname !== "/cart" &&
                <Footer />
            }

            <ModalCart
                visible={openModalCart}
                onClose={() => setOpenModalCart(false)}
            />

            <ModalMenu
                visible={openModalMenu}
                onClose={() => setOpenModalMenu(false)}
            />

            <Toaster />
        </>
    )
}
